import:
  - ~/.config/alacritty/catppuccin/catppuccin-macchiato.yml

env:
  TERM: xterm-256color

window:
  decorations: buttonless
  opacity: 0.97
  startup_mode: Windowed
  dynamic_title: true
  history: 10000
  multiplier: 3
  dynamic_padding: true

font:
  normal:
    family: SauceCodePro Nerd Font Mono

  size: 14.0
  builtin_box_drawing: true

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"

  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: false

key_bindings:
  - { key: Comma,    mods: Command,      command: {program: "sh", args: ["-c","nvim ~/.config/alacritty/alacritty.yml"]} }
  - { key: N,        mods: Command,      action: SpawnNewInstance       }
  - { key: Space,    mods: Alt,          chars: " "                     }
  - { key: Back,     mods: Super|Control, chars: "\x15"                 } # delete word/line (cmd/ctrl backspace)
  - { key: Left,     mods: Shift,     chars: "\x1bb"                    } # one word left (shift left)
  - { key: Right,    mods: Shift,     chars: "\x1bf"                    } # one word right (shift right)
  - { key: Left,     mods: Command, chars: "\x1bOH",   mode: AppCursor  } # Home (cmd left)
  - { key: Right,    mods: Command, chars: "\x1bOF",   mode: AppCursor  } # End (cmd right)