schemes:
  # Tokyo Night theme, based on both:
  #   https://github.com/ghifarit53/tokyonight-vim
  #   https://github.com/enkia/tokyo-night-vscode-theme
  tokyo-night: &tokyo-night
    # Default colors
    primary:
      background: '0x1a1b26'
      foreground: '0xa9b1d6'
    # Normal colors
    normal:
      black: '0x32344a'
      red: '0xf7768e'
      green: '0x9ece6a'
      yellow: '0xe0af68'
      blue: '0x7aa2f7'
      magenta: '0xad8ee6'
      cyan: '0x449dab'
      white: '0x787c99'
    # Bright colors
    bright:
      black: '0x444b6a'
      red: '0xff7a93'
      green: '0xb9f27c'
      yellow: '0xff9e64'
      blue: '0x7da6ff'
      magenta: '0xbb9af7'
      cyan: '0x0db9d7'
      white: '0xacb0d0'
  tokyo-night-storm: &tokyo-night-storm
    # Default colors
    primary:
      background: '0x24283b'
      foreground: '0xa9b1d6'
    # Normal colors
    normal:
      black: '0x32344a'
      red: '0xf7768e'
      green: '0x9ece6a'
      yellow: '0xe0af68'
      blue: '0x7aa2f7'
      magenta: '0xad8ee6'
      cyan: '0x449dab'
      white: '0x9699a8'
    # Bright colors
    bright:
      black: '0x444b6a'
      red: '0xff7a93'
      green: '0xb9f27c'
      yellow: '0xff9e64'
      blue: '0x7da6ff'
      magenta: '0xbb9af7'
      cyan: '0x0db9d7'
      white: '0xacb0d0'
  catppuccin-frappe: &catppuccin-frappe
    # Default colors
    primary:
      background: "#303446" # base
      foreground: "#C6D0F5" # text
      # Bright and dim foreground colors
      dim_foreground: "#C6D0F5" # text
      bright_foreground: "#C6D0F5" # text
    # Cursor colors
    cursor:
      text: "#303446" # base
      cursor: "#F2D5CF" # rosewater
    vi_mode_cursor:
      text: "#303446" # base
      cursor: "#BABBF1" # lavender
    # Search colors
    search:
      matches:
        foreground: "#303446" # base
        background: "#A5ADCE" # subtext0
      focused_match:
        foreground: "#303446" # base
        background: "#A6D189" # green
      footer_bar:
        foreground: "#303446" # base
        background: "#A5ADCE" # subtext0
    # Keyboard regex hints
    hints:
      start:
        foreground: "#303446" # base
        background: "#E5C890" # yellow
      end:
        foreground: "#303446" # base
        background: "#A5ADCE" # subtext0
    # Selection colors
    selection:
      text: "#303446" # base
      background: "#F2D5CF" # rosewater
    # Normal colors
    normal:
      black: "#51576D" # surface1
      red: "#E78284" # red
      green: "#A6D189" # green
      yellow: "#E5C890" # yellow
      blue: "#8CAAEE" # blue
      magenta: "#F4B8E4" # pink
      cyan: "#81C8BE" # teal
      white: "#B5BFE2" # subtext1
    # Bright colors
    bright:
      black: "#626880" # surface2
      red: "#E78284" # red
      green: "#A6D189" # green
      yellow: "#E5C890" # yellow
      blue: "#8CAAEE" # blue
      magenta: "#F4B8E4" # pink
      cyan: "#81C8BE" # teal
      white: "#A5ADCE" # subtext0
    # Dim colors
    dim:
      black: "#51576D" # surface1
      red: "#E78284" # red
      green: "#A6D189" # green
      yellow: "#E5C890" # yellow
      blue: "#8CAAEE" # blue
      magenta: "#F4B8E4" # pink
      cyan: "#81C8BE" # teal
      white: "#B5BFE2" # subtext1
    indexed_colors:
      - {index: 16, color: "#EF9F76"}
      - {index: 17, color: "#F2D5CF"}
  catppuccin-mocha: &catppuccin-mocha
    primary:
      background: "#1E1E2E" # base
      foreground: "#CDD6F4" # text
      # Bright and dim foreground colors
      dim_foreground: "#CDD6F4" # text
      bright_foreground: "#CDD6F4" # text
    # Cursor colors
    cursor:
      text: "#1E1E2E" # base
      cursor: "#F5E0DC" # rosewater
    vi_mode_cursor:
      text: "#1E1E2E" # base
      cursor: "#B4BEFE" # lavender
    # Search colors
    search:
      matches:
        foreground: "#1E1E2E" # base
        background: "#A6ADC8" # subtext0
      focused_match:
        foreground: "#1E1E2E" # base
        background: "#A6E3A1" # green
      footer_bar:
        foreground: "#1E1E2E" # base
        background: "#A6ADC8" # subtext0
    # Keyboard regex hints
    hints:
      start:
        foreground: "#1E1E2E" # base
        background: "#F9E2AF" # yellow
      end:
        foreground: "#1E1E2E" # base
        background: "#A6ADC8" # subtext0
    # Selection colors
    selection:
      text: "#1E1E2E" # base
      background: "#F5E0DC" # rosewater
    # Normal colors
    normal:
      black: "#45475A" # surface1
      red: "#F38BA8" # red
      green: "#A6E3A1" # green
      yellow: "#F9E2AF" # yellow
      blue: "#89B4FA" # blue
      magenta: "#F5C2E7" # pink
      cyan: "#94E2D5" # teal
      white: "#BAC2DE" # subtext1
    # Bright colors
    bright:
      black: "#585B70" # surface2
      red: "#F38BA8" # red
      green: "#A6E3A1" # green
      yellow: "#F9E2AF" # yellow
      blue: "#89B4FA" # blue
      magenta: "#F5C2E7" # pink
      cyan: "#94E2D5" # teal
      white: "#A6ADC8" # subtext0
    # Dim colors
    dim:
      black: "#45475A" # surface1
      red: "#F38BA8" # red
      green: "#A6E3A1" # green
      yellow: "#F9E2AF" # yellow
      blue: "#89B4FA" # blue
      magenta: "#F5C2E7" # pink
      cyan: "#94E2D5" # teal
      white: "#BAC2DE" # subtext1
    indexed_colors:
      - {index: 16, color: "#FAB387"}
      - {index: 17, color: "#F5E0DC"}
  # Colors (Material Theme)
  material: &material
    # Default colors
    primary:
      background: '0x1e282d'
      foreground: '0xc4c7d1'
    # Normal colors
    normal:
      black: '0x666666'
      red: '0xeb606b'
      green: '0xc3e88d'
      yellow: '0xf7eb95'
      blue: '0x80cbc4'
      magenta: '0xff2f90'
      cyan: '0xaeddff'
      white: '0xffffff'
    # Bright colors
    bright:
      black: '0xff262b'
      red: '0xeb606b'
      green: '0xc3e88d'
      yellow: '0xf7eb95'
      blue: '0x7dc6bf'
      magenta: '0x6c71c4'
      cyan: '0x35434d'
      white: '0xffffff'
  # Colors (Monokai Pro)
  monokai-pro: &monokai-pro
    # Default colors
    primary:
      background: '#2D2A2E'
      foreground: '#FCFCFA'
    # Normal colors
    normal:
      black: '#403E41'
      red: '#FF6188'
      green: '#A9DC76'
      yellow: '#FFD866'
      blue: '#FC9867'
      magenta: '#AB9DF2'
      cyan: '#78DCE8'
      white: '#FCFCFA'
    # Bright colors
    bright:
      black: '#727072'
      red: '#FF6188'
      green: '#A9DC76'
      yellow: '#FFD866'
      blue: '#FC9867'
      magenta: '#AB9DF2'
      cyan: '#78DCE8'
      white: '#FCFCFA'
  # The 'Dark dimmed' colorscheme from Github.
  github: &github
    primary:
      background: '#2d333b'
      foreground: '#adbac7'
    normal:
      black: '#2d333b'
      red: '#f47067'
      green: '#8ddb8c'
      yellow: '#f69d50'
      blue: '#6cb6ff'
      magenta: '#dcbdfb'
      cyan: '#96d0ff'
      white: '#adbac7'
    bright:
      black: '#768390'
      red: '#f47067'
      green: '#8ddb8c'
      yellow: '#f69d50'
      blue: '#6cb6ff'
      magenta: '#dcbdfb'
      cyan: '#96d0ff'
      white: '#adbac7'
  # Colors (Dracula)
  dracula: &dracula
    # Default colors
    primary:
      background: '#282a36'
      foreground: '#f8f8f2'
    # Normal colors
    normal:
      black: '#000000'
      red: '#ff5555'
      green: '#50fa7b'
      yellow: '#f1fa8c'
      blue: '#caa9fa'
      magenta: '#ff79c6'
      cyan: '#8be9fd'
      white: '#bfbfbf'
    # Bright colors
    bright:
      black: '#575b70'
      red: '#ff6e67'
      green: '#5af78e'
      yellow: '#f4f99d'
      blue: '#caa9fa'
      magenta: '#ff92d0'
      cyan: '#9aedfe'
      white: '#e6e6e6'
  # Colors (Gruvbox light)
  gruvbox-light: &gruvbox-light
    # Default colors
    primary:
      # hard contrast: background = '#f9f5d7'
      background: '#fbf1c7'
      # soft contrast: background = '#f2e5bc'
      foreground: '#3c3836'
    # Normal colors
    normal:
      black: '#fbf1c7'
      red: '#cc241d'
      green: '#98971a'
      yellow: '#d79921'
      blue: '#458588'
      magenta: '#b16286'
      cyan: '#689d6a'
      white: '#7c6f64'
    # Bright colors
    bright:
      black: '#928374'
      red: '#9d0006'
      green: '#79740e'
      yellow: '#b57614'
      blue: '#076678'
      magenta: '#8f3f71'
      cyan: '#427b58'
      white: '#3c3836'
  # Colors (Gruvbox dark)
  gruvbox-dark: &gruvbox-dark
    primary:
      # hard contrast background - '#1d2021'
      background: &gruvbox_dark_bg '#282828'
      # soft contrast background - '#32302f'
      foreground: '#ebdbb2'
      bright_foreground: '#fbf1c7'
      dim_foreground: '#a89984'
    cursor:
      text: CellBackground
      cursor: CellForeground
    vi_mode_cursor:
      text: CellBackground
      cursor: CellForeground
    # search:
    #   matches:
    #     foreground: '#000000'
    #     background: '#ffffff'
    #   focused_match:
    #    foreground: CellBackground
    #    background: CellForeground
    #   bar:
    #     background: ''
    #     foreground: ''
    # line_indicator:
    #   foreground: None
    #   background: None
    selection:
      text: CellBackground
      background: CellForeground
    bright:
      black: '#928374'
      red: '#fb4934'
      green: '#b8bb26'
      yellow: '#fabd2f'
      blue: '#83a598'
      magenta: '#d3869b'
      cyan: '#8ec07c'
      white: '#ebdbb2'
    normal:
      black: *gruvbox_dark_bg
      red: '#cc241d'
      green: '#98971a'
      yellow: '#d79921'
      blue: '#458588'
      magenta: '#b16286'
      cyan: '#689d6a'
      white: '#a89984'
    dim:
      black: '#32302f'
      red: '#9d0006'
      green: '#79740e'
      yellow: '#b57614'
      blue: '#076678'
      magenta: '#8f3f71'
      cyan: '#427b58'
      white: '#928374'
    indexed_colors:
      - {index: 66, color: '#458588'}
      - {index: 72, color: '#689d6a'}
      - {index: 106, color: '#98971a'}
      - {index: 108, color: '#8ec07c'}
      - {index: 109, color: '#83a598'}
      - {index: 124, color: '#cc241d'}
      - {index: 132, color: '#b16286'}
      - {index: 142, color: '#b8bb26'}
      - {index: 166, color: '#d65d0e'}
      - {index: 167, color: '#fb4934'}
      - {index: 172, color: '#d79921'}
      - {index: 175, color: '#d3869b'}
      - {index: 208, color: '#fe8019'}
      - {index: 214, color: '#fabd2f'}
      - {index: 223, color: '#ebdbb2'}
      - {index: 229, color: '#fbf1c7'}
      - {index: 234, color: '#1d2021'}
      - {index: 235, color: '#282828'}
      - {index: 236, color: '#32302f'}
      - {index: 237, color: '#3c3836'}
      - {index: 239, color: '#504945'}
      - {index: 241, color: '#665c54'}
      - {index: 243, color: '#7c6f64'}
      - {index: 245, color: '#928374'}
      - {index: 246, color: '#a89984'}
      - {index: 248, color: '#bdae93'}
      - {index: 250, color: '#d5c4a1'}
  # Colors (Nord)
  nord: &nord
    # Default colors
    primary:
      background: '#2E3440'
      foreground: '#D8DEE9'
    # Normal colors
    normal:
      black: '#3B4252'
      red: '#BF616A'
      green: '#A3BE8C'
      yellow: '#EBCB8B'
      blue: '#81A1C1'
      magenta: '#B48EAD'
      cyan: '#88C0D0'
      white: '#E5E9F0'
    # Bright colors
    bright:
      black: '#4C566A'
      red: '#BF616A'
      green: '#A3BE8C'
      yellow: '#EBCB8B'
      blue: '#81A1C1'
      magenta: '#B48EAD'
      cyan: '#8FBCBB'
      white: '#ECEFF4'
  zenburn: &zenburn
    primary:
      background: '#333333'
      foreground: '#ffffff'
      bright_foreground: '#ffffff'
      bright_background: '#555555'
    cursor:
      text: '#000000'
      cursor: '#00ff00'
    normal:
      black: '#4d4d4d'
      red: '#bb0000'
      green: '#98f898'
      yellow: '#f0e68c'
      blue: '#96853f'
      magenta: '#ffdead'
      cyan: '#ffa0a0'
      white: '#f5deb3'
    bright:
      black: '#555555'
      red: '#ff5555'
      green: '#55ff55'
      yellow: '#ffff55'
      blue: '#87ceeb'
      magenta: '#ff55ff'
      cyan: '#ffd700'
      white: '#ffffff'
colors: *dracula
