schemes:
  # Tokyo Night theme, based on both:
  #   https://github.com/ghifarit53/tokyonight-vim
  #   https://github.com/enkia/tokyo-night-vscode-theme
  tokyo-night: &tokyo-night
    # Default colors
    primary:
      background: '0x1a1b26'
      foreground: '0xa9b1d6'
    # Normal colors
    normal:
      black: '0x32344a'
      red: '0xf7768e'
      green: '0x9ece6a'
      yellow: '0xe0af68'
      blue: '0x7aa2f7'
      magenta: '0xad8ee6'
      cyan: '0x449dab'
      white: '0x787c99'
    # Bright colors
    bright:
      black: '0x444b6a'
      red: '0xff7a93'
      green: '0xb9f27c'
      yellow: '0xff9e64'
      blue: '0x7da6ff'
      magenta: '0xbb9af7'
      cyan: '0x0db9d7'
      white: '0xacb0d0'
  tokyo-night-storm: &tokyo-night-storm
    # Default colors
    primary:
      background: '0x24283b'
      foreground: '0xa9b1d6'
    # Normal colors
    normal:
      black: '0x32344a'
      red: '0xf7768e'
      green: '0x9ece6a'
      yellow: '0xe0af68'
      blue: '0x7aa2f7'
      magenta: '0xad8ee6'
      cyan: '0x449dab'
      white: '0x9699a8'
    # Bright colors
    bright:
      black: '0x444b6a'
      red: '0xff7a93'
      green: '0xb9f27c'
      yellow: '0xff9e64'
      blue: '0x7da6ff'
      magenta: '0xbb9af7'
      cyan: '0x0db9d7'
      white: '0xacb0d0'
  catppuccin-frappe: &catppuccin-frappe
    # Default colors
    primary:
      background: "#303446" # base
      foreground: "#C6D0F5" # text
      # Bright and dim foreground colors
      dim_foreground: "#C6D0F5" # text
      bright_foreground: "#C6D0F5" # text
    # Cursor colors
    cursor:
      text: "#303446" # base
      cursor: "#F2D5CF" # rosewater
    vi_mode_cursor:
      text: "#303446" # base
      cursor: "#BABBF1" # lavender
    # Search colors
    search:
      matches:
        foreground: "#303446" # base
        background: "#A5ADCE" # subtext0
      focused_match:
        foreground: "#303446" # base
        background: "#A6D189" # green
      footer_bar:
        foreground: "#303446" # base
        background: "#A5ADCE" # subtext0
    # Keyboard regex hints
    hints:
      start:
        foreground: "#303446" # base
        background: "#E5C890" # yellow
      end:
        foreground: "#303446" # base
        background: "#A5ADCE" # subtext0
    # Selection colors
    selection:
      text: "#303446" # base
      background: "#F2D5CF" # rosewater
    # Normal colors
    normal:
      black: "#51576D" # surface1
      red: "#E78284" # red
      green: "#A6D189" # green
      yellow: "#E5C890" # yellow
      blue: "#8CAAEE" # blue
      magenta: "#F4B8E4" # pink
      cyan: "#81C8BE" # teal
      white: "#B5BFE2" # subtext1
    # Bright colors
    bright:
      black: "#626880" # surface2
      red: "#E78284" # red
      green: "#A6D189" # green
      yellow: "#E5C890" # yellow
      blue: "#8CAAEE" # blue
      magenta: "#F4B8E4" # pink
      cyan: "#81C8BE" # teal
      white: "#A5ADCE" # subtext0
    # Dim colors
    dim:
      black: "#51576D" # surface1
      red: "#E78284" # red
      green: "#A6D189" # green
      yellow: "#E5C890" # yellow
      blue: "#8CAAEE" # blue
      magenta: "#F4B8E4" # pink
      cyan: "#81C8BE" # teal
      white: "#B5BFE2" # subtext1
    indexed_colors:
      - {index: 16, color: "#EF9F76"}
      - {index: 17, color: "#F2D5CF"}
  catppuccin-mocha: &catppuccin-mocha
    primary:
      background: "#1E1E2E" # base
      foreground: "#CDD6F4" # text
      # Bright and dim foreground colors
      dim_foreground: "#CDD6F4" # text
      bright_foreground: "#CDD6F4" # text
    # Cursor colors
    cursor:
      text: "#1E1E2E" # base
      cursor: "#F5E0DC" # rosewater
    vi_mode_cursor:
      text: "#1E1E2E" # base
      cursor: "#B4BEFE" # lavender
    # Search colors
    search:
      matches:
        foreground: "#1E1E2E" # base
        background: "#A6ADC8" # subtext0
      focused_match:
        foreground: "#1E1E2E" # base
        background: "#A6E3A1" # green
      footer_bar:
        foreground: "#1E1E2E" # base
        background: "#A6ADC8" # subtext0
    # Keyboard regex hints
    hints:
      start:
        foreground: "#1E1E2E" # base
        background: "#F9E2AF" # yellow
      end:
        foreground: "#1E1E2E" # base
        background: "#A6ADC8" # subtext0
    # Selection colors
    selection:
      text: "#1E1E2E" # base
      background: "#F5E0DC" # rosewater
    # Normal colors
    normal:
      black: "#45475A" # surface1
      red: "#F38BA8" # red
      green: "#A6E3A1" # green
      yellow: "#F9E2AF" # yellow
      blue: "#89B4FA" # blue
      magenta: "#F5C2E7" # pink
      cyan: "#94E2D5" # teal
      white: "#BAC2DE" # subtext1
    # Bright colors
    bright:
      black: "#585B70" # surface2
      red: "#F38BA8" # red
      green: "#A6E3A1" # green
      yellow: "#F9E2AF" # yellow
      blue: "#89B4FA" # blue
      magenta: "#F5C2E7" # pink
      cyan: "#94E2D5" # teal
      white: "#A6ADC8" # subtext0
    # Dim colors
    dim:
      black: "#45475A" # surface1
      red: "#F38BA8" # red
      green: "#A6E3A1" # green
      yellow: "#F9E2AF" # yellow
      blue: "#89B4FA" # blue
      magenta: "#F5C2E7" # pink
      cyan: "#94E2D5" # teal
      white: "#BAC2DE" # subtext1
    indexed_colors:
      - {index: 16, color: "#FAB387"}
      - {index: 17, color: "#F5E0DC"}
  # Colors (Material Theme)
  material: &material
    # Default colors
    primary:
      background: '#263238'
      foreground: '#eeffff'
    # Normal colors
    normal:
      black: '#000000' # Arbitrary
      red: '#e53935'
      green: '#91b859'
      yellow: '#ffb62c'
      blue: '#6182b8'
      magenta: '#ff5370' # Dark pink of the original material theme
      cyan: '#39adb5'
      white: '#a0a0a0' # Arbitrary
    # Bright colors
    bright:
      black: '#4e4e4e' # Arbitrary
      red: '#ff5370'
      green: '#c3e88d'
      yellow: '#ffcb6b'
      blue: '#82aaff'
      magenta: '#f07178' # Pink of the original material theme
      cyan: '#89ddff'
      white: '#ffffff' # Arbitrary
  # Colors (Monokai Pro)
  monokai-pro: &monokai-pro
    # Default colors
    primary:
      background: '#2D2A2E'
      foreground: '#FCFCFA'
    # Normal colors
    normal:
      black: '#403E41'
      red: '#FF6188'
      green: '#A9DC76'
      yellow: '#FFD866'
      blue: '#FC9867'
      magenta: '#AB9DF2'
      cyan: '#78DCE8'
      white: '#FCFCFA'
    # Bright colors
    bright:
      black: '#727072'
      red: '#FF6188'
      green: '#A9DC76'
      yellow: '#FFD866'
      blue: '#FC9867'
      magenta: '#AB9DF2'
      cyan: '#78DCE8'
      white: '#FCFCFA'
colors: *monokai-pro
