tap "charmbracelet/tap"
tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/services"
tap "eth-p/software"
tap "go-task/tap"
tap "jesseduffield/lazygit"

# CLI apps
brew "asdf"
brew "ansible"
brew "argocd"
brew "awscli"
brew "bat"
brew "bitwarden-cli"
brew "bpytop"
brew "charmbracelet/tap/glow"
brew "charmbracelet/tap/gum"
brew "charmbracelet/tap/mods"
brew "charmbracelet/tap/vhs"
brew "cloudflare-wrangler2"
brew "cmctl"
brew "cowsay"
brew "dateutils"
brew "duf"
brew "eth-p/software/bat-extras"
brew "exa"
brew "fd"
brew "fzf"
brew "go-task/tap/go-task"
brew "gh"
brew "git"
brew "git-delta"
brew "gitleaks"
brew "helix"
brew "helm"
brew "htop"
brew "httpie"
brew "hugo"
brew "jc"
brew "jesseduffield/lazygit/lazygit"
brew "jq"
brew "kubectx"
brew "lf"
brew "mas"
brew "mcfly"
brew "navi"
brew "neovim"
brew "ripgrep"
brew "terraform"
brew "terragrunt"
brew "thefuck"
brew "tldr"
brew "tmux"
brew "tree"
brew "wget"
brew "yt-dlp"
brew "yq"
brew "zsh"

# Casks (GUI Apps)
cask "alacritty"
cask "alt-tab"
cask "amethyst"
cask "authy"
cask "bartender"
cask "cron"
cask "dash"
cask "figma"
cask "firefox"
cask "gimp"
cask "google-chrome"
cask "google-drive"
cask "linearmouse"
cask "macdown"
cask "mimestream"
cask "ngrok"
cask "obsidian"
cask "rancher"
cask "raycast"
cask "shottr"
cask "ticktick"
cask "vlc"
cask "visual-studio-code"

# Flutter dev
cask "flutter"
cask "android-studio"

# Fonts
cask "font-hack-nerd-font"
cask "font-inconsolata-for-powerline"
cask "font-jetbrains-mono-nerd-font"
cask "font-menlo-for-powerline"
cask "font-meslo-lg-nerd-font"
cask "font-sauce-code-pro-nerd-font"

# Mac App Store Apps
mas "Amphetamine", id: 937984704
mas "Friendly Streaming", id: 553245401
mas "Gestimer", id: 990588172
mas "Kindle", id: 405399194
mas "Microsoft Remote Desktop", id: 1295203466
mas "Tailscale", id: 1475387142
mas "ToothFairy", id: 1191449274
mas "Trello", id: 1278508951
mas "rcmd", id: 1596283165
mas "Flow", id: 1423210932