tap "charmbracelet/tap"
tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"

# CLI apps
brew "asciinema"
brew "asdf"
brew "ansible"
brew "awscli"
brew "bat"
brew "bpytop"
brew "charmbracelet/tap/glow"
brew "charmbracelet/tap/gum"
brew "cowsay"
brew "duf"
brew "eth-p/software/bat-extras"
brew "exa"
brew "fd"
brew "fzf"
brew "git"
brew "git-delta"
brew "helix"
brew "helm"
brew "htop"
brew "httpie"
brew "hugo"
brew "jc"
brew "jq"
brew "kubernetes-cli"
brew "kubectx"
brew "lf"
brew "mas"
brew "mcfly"
brew "navi"
brew "neovim"
brew "ripgrep"
brew "terraform"
brew "thefuck"
brew "tldr"
brew "tmux"
brew "tree"
brew "wget"
brew "yt-dlp"
brew "yq"
brew "zsh"

# Casks (GUI Apps)
cask "alacritty"
cask "alfred"
cask "alt-tab"
cask "authy"
cask "bartender"
cask "brave-browser"
cask "dash"
cask "figma"
cask "firefox"
cask "gimp"
cask "google-chrome"
cask "google-drive"
cask "linearmouse"
cask "macdown"
cask "mimestream"
cask "ngrok"
cask "obsidian"
cask "rectangle"
cask "skitch"
cask "spotify"
cask "vlc"
cask "visual-studio-code"

# Fonts
cask "font-hack-nerd-font"
cask "font-inconsolata-for-powerline"
cask "font-menlo-for-powerline"
cask "font-meslo-lg-nerd-font"
cask "font-sauce-code-pro-nerd-font"

# Mac App Store Apps
mas "Amphetamine", id: 937984704
mas "Friendly Streaming", id: 553245401
mas "Gestimer", id: 990588172
mas "Kindle", id: 405399194
mas "Microsoft Remote Desktop", id: 1295203466
mas "Parcel", id: 639968404
mas "Tailscale", id: 1475387142
mas "ToothFairy", id: 1191449274
mas "Trello", id: 1278508951