tap "charmbracelet/tap"
tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"

# CLI apps
brew "asciinema"
brew "asdf"
brew "ansible"
brew "awscli"
brew "bat"
brew "bpytop"
brew "guile"
brew "gnutls"
brew "cask"
brew "cfssl"
brew "charmbracelet/tap/glow"
brew "charmbracelet/tap/gum"
brew "cowsay"
brew "diff-so-fancy"
brew "duf"
brew "fd"
brew "fzf"
brew "git"
brew "go"
brew "gopls"
brew "helix"
brew "helm"
brew "htop"
brew "httpie"
brew "hugo"
brew "jc"
brew "jq"
brew "kubernetes-cli"
brew "kubectx"
brew "mas"
brew "mcfly"
brew "neovim"
brew "ripgrep"
brew "terraform"
brew "thefuck"
brew "tldr"
brew "tmux"
brew "tree"
brew "wget"
brew "yq"
brew "zlib"
brew "zsh"

# Casks (GUI Apps)
cask "alfred"
cask "alt-tab"
cask "authy"
cask "bartender"
cask "dash"
cask "fig"
cask "figma"
cask "flux"
cask "gimp"
cask "google-chrome"
cask "google-drive"
cask "hyper"
cask "linearmouse"
cask "macdown"
cask "obsidian"
cask "rectangle"
cask "skitch"
cask "spotify"
cask "vlc"
cask "visual-studio-code"
cask "ytmdesktop-youtube-music"

# Fonts
cask "font-hack-nerd-font"
cask "font-inconsolata-for-powerline"
cask "font-menlo-for-powerline"
cask "homebrew/cask-fonts/font-meslo-lg-nerd-font"

# Mac App Store Apps
mas "Amphetamine", id: 937984704
mas "Trello", id: 1278508951
mas "Kindle", id: 405399194
mas "Gestimer", id: 990588172
mas "Microsoft Remote Desktop", id: 1295203466
mas "ToothFairy", id: 1191449274
