# Use tall and fullscreen layouts
layouts:
    - widescreen-tall
    - widescreen-tall-right
    - two-pane
    - fullscreen
    - wide

mod1:
    - option
    - shift
mod2:
    - option
    - shift
    - control

mouse-resizes-windows: true
mouse-swaps-windows: true

# Add 10px margin between windows
window-margins: true
window-margin-size: 10