# Use tall and fullscreen layouts
layouts:
    - widescreen-tall
    - widescreen-tall-right
    - two-pane
    - fullscreen
    - row

mod1:
    - option
    - shift
mod2:
    - option
    - shift
    - control

floating:
    - "com.apple.systempreferences"

mouse-resizes-windows: true
mouse-swaps-windows: true

# Add 10px margin between windows
window-margins: true
window-margin-size: 10

# Top padding needed if using sketchybar
# screen-padding-top: 45