# Use tall and fullscreen layouts
layouts:
    - two-pane
    - fullscreen
    - widescreen-tall
    - widescreen-tall-right
    - row
    - wide
    - 3column-left
    - middle-wide
    - 3column-right

mod1:
    - option
    - shift
mod2:
    - option
    - shift
    - control

floating:
    - "com.apple.systempreferences"
    - "org.videolan.vlc"
    - "com.valvesoftware.steam"
    - "com.teamviewer.TeamViewer"
    - "com.authy.authy-mac"
    - "com.tann.dice.desktop"
    - "com.philandro.anydesk"
    - "com.electron.moonitor"

mouse-resizes-windows: true
mouse-swaps-windows: true

# Add 10px margin between windows
window-margins: true
window-margin-size: 10

# Top padding needed if using sketchybar
# screen-padding-top: 45