source_if_exists () {
    if test -r "$1"; then
        source "$1"
    fi
}

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
source_if_exists "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
source_if_exists "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
source_if_exists ~/.fzf.zsh
source_if_exists ~/.p10k.zsh

# Prompt
prompt powerlevel10k

# Custom Functions
fpath=(~/.func $fpath)
autoload -Uz pods help kp tm gig ath switchdesktop

# Auto completions
autoload -U +X bashcompinit && bashcompinit
autoload -U compinit
compinit
complete -o nospace -C /usr/local/bin/terraform terraform

# Mcfly for better searching of history with ctrl+R
eval "$(mcfly init zsh)"

# Set up 'fuck' alias for thefuck corrections
eval $(thefuck --alias)

# Set up 'navi' for ctrl+G cheatsheets
eval "$(navi widget zsh)"

# asdf
. /usr/local/opt/asdf/libexec/asdf.sh

# Update go paths, should use the asdf golang shim's location
export GOPATH=$(go env GOPATH)
export GOROOT=$(go env GOROOT)
export GOBIN=$(go env GOBIN)
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOROOT/bin
export PATH=$PATH:$GOBIN

source_if_exists ~/.aliases.zsh